# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LevelMetaData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LevelMetaData.proto',
  package='NetLevel',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13LevelMetaData.proto\x12\x08NetLevel\"\xb1\x01\n\rLevelMetaData\x12\x14\n\x0clocalLevelId\x18\x01 \x01(\x05\x12\x15\n\runiqueLevelId\x18\x02 \x01(\x03\x12\x10\n\x08\x46ullName\x18\x03 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x04 \x01(\t\x12\x11\n\tavailBlue\x18\x05 \x01(\x08\x12\x13\n\x0b\x61vailYellow\x18\x06 \x01(\x08\x12\x10\n\x08\x61vailRed\x18\x07 \x01(\x08\x12\x12\n\navailGreen\x18\x08 \x01(\x08\x62\x06proto3'
)




_LEVELMETADATA = _descriptor.Descriptor(
  name='LevelMetaData',
  full_name='NetLevel.LevelMetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='localLevelId', full_name='NetLevel.LevelMetaData.localLevelId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uniqueLevelId', full_name='NetLevel.LevelMetaData.uniqueLevelId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FullName', full_name='NetLevel.LevelMetaData.FullName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Description', full_name='NetLevel.LevelMetaData.Description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='availBlue', full_name='NetLevel.LevelMetaData.availBlue', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='availYellow', full_name='NetLevel.LevelMetaData.availYellow', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='availRed', full_name='NetLevel.LevelMetaData.availRed', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='availGreen', full_name='NetLevel.LevelMetaData.availGreen', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['LevelMetaData'] = _LEVELMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LevelMetaData = _reflection.GeneratedProtocolMessageType('LevelMetaData', (_message.Message,), {
  'DESCRIPTOR' : _LEVELMETADATA,
  '__module__' : 'LevelMetaData_pb2'
  # @@protoc_insertion_point(class_scope:NetLevel.LevelMetaData)
  })
_sym_db.RegisterMessage(LevelMetaData)


# @@protoc_insertion_point(module_scope)
