# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LevelMetaDataList.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LevelMetaData_pb2 as LevelMetaData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LevelMetaDataList.proto',
  package='NetLevel',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17LevelMetaDataList.proto\x12\x08NetLevel\x1a\x13LevelMetaData.proto\"B\n\x11LevelMetaDataList\x12-\n\x0clocalLevelId\x18\x01 \x03(\x0b\x32\x17.NetLevel.LevelMetaDatab\x06proto3'
  ,
  dependencies=[LevelMetaData__pb2.DESCRIPTOR,])




_LEVELMETADATALIST = _descriptor.Descriptor(
  name='LevelMetaDataList',
  full_name='NetLevel.LevelMetaDataList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='localLevelId', full_name='NetLevel.LevelMetaDataList.localLevelId', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=124,
)

_LEVELMETADATALIST.fields_by_name['localLevelId'].message_type = LevelMetaData__pb2._LEVELMETADATA
DESCRIPTOR.message_types_by_name['LevelMetaDataList'] = _LEVELMETADATALIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LevelMetaDataList = _reflection.GeneratedProtocolMessageType('LevelMetaDataList', (_message.Message,), {
  'DESCRIPTOR' : _LEVELMETADATALIST,
  '__module__' : 'LevelMetaDataList_pb2'
  # @@protoc_insertion_point(class_scope:NetLevel.LevelMetaDataList)
  })
_sym_db.RegisterMessage(LevelMetaDataList)


# @@protoc_insertion_point(module_scope)
