name: Backend to Dockerhub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the backend Docker image
      run: docker build -t mineorbit/dungeonsanddungeonslevelserver backend
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: mineorbit
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Push to Docker Hub backend
      run: docker push mineorbit/dungeonsanddungeonslevelserver
      
